# Generated by Django 3.2 on 2021-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlineurl',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='offlineurl',
            name='opcional_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
